# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkgJpsrPLf54vXV3wMqcJXu2RLl27OGj
"""

import streamlit as st
import numpy as np
import pandas as pd
import joblib
import datetime
import pytz
import plotly.express as px
import os

# Cargar el modelo .pkl
modelo = joblib.load("PC_0.8722_12.04.pkl")

# Archivo temporal para guardar predicciones
historial_path = "historial_predicciones.csv"
if not os.path.exists(historial_path):
    pd.DataFrame(columns=["FechaHora", "Cenizas", "PC"]).to_csv(historial_path, index=False)

# Título de la app
st.title("🔥 Predicción del Poder Calorífico del Carbón")
st.markdown("Ingrese los datos manualmente o pegue una fila completa separada por **coma, espacio o tabulación**.")

# Opción de entrada rápida
st.subheader("📋 Entrada rápida (una línea completa)")
entrada_linea = st.text_input("Pegue aquí una fila completa con los 11 valores en orden:")

# Botón para activar la entrada manual
mostrar_entrada_manual = st.button("📝 Mostrar entrada manual")

# Si se presiona el botón, se muestran los campos de entrada manual
if mostrar_entrada_manual:
    cenizas_bs = st.number_input("Cenizas (BS) (%)", min_value=0.0)
    sio2 = st.number_input("SiO2 ash (%)", min_value=0.0)
    al2o3 = st.number_input("Al2O3 ash (%)", min_value=0.0)
    fe2o3 = st.number_input("Fe2O3 ash (%)", min_value=0.0)
    cao = st.number_input("CaO ash (%)", min_value=0.0)
    mgo = st.number_input("MgO ash (%)", min_value=0.0)
    so3 = st.number_input("SO3 ash (%)", min_value=0.0)
    na2o = st.number_input("Na2O ash (%)", min_value=0.0)
    k2o = st.number_input("K2O ash (%)", min_value=0.0)
    s_carbon = st.number_input("S carbón (%)", min_value=0.0)
    cl_carbon = st.number_input("Cl carbón (%)", min_value=0.0)

# Botón de predicción
if st.button("🔮 Predecir Poder Calorífico"):
    if entrada_linea:
        if "," in entrada_linea:
            sep = ","
        elif "\t" in entrada_linea:
            sep = "\t"
        else:
            sep = " "
        try:
            valores = list(map(float, entrada_linea.strip().split(sep)))
            if len(valores) != 11:
                st.error("⚠️ Debe ingresar exactamente 11 valores.")
                st.stop()
        except:
            st.error("⚠️ Error en el formato de la línea pegada.")
            st.stop()
    else:
        valores = [cenizas_bs, sio2, al2o3, fe2o3, cao, mgo, so3, na2o, k2o, s_carbon, cl_carbon]

    valores_np = np.array(valores).reshape(1, -1)
    pc_predicho = modelo.predict(valores_np)[0]
    pc_entero = int(round(pc_predicho))

    st.success(f"🔥 Poder Calorífico Predicho: **{pc_entero} kcal/kg**")

    nuevo = pd.DataFrame([{
        "FechaHora": datetime.datetime.now(pytz.timezone('America/Lima')).strftime('%Y-%m-%d %H:%M:%S'),
        "Cenizas": valores[0],
        "PC": pc_entero
    }])
    historial = pd.read_csv(historial_path)
    historial = pd.concat([historial, nuevo], ignore_index=True).tail(20)
    historial.to_csv(historial_path, index=False)

# Mostrar gráfico
if os.path.exists(historial_path):
    historial = pd.read_csv(historial_path)

    if not historial.empty:
        # Convertir fecha a datetime y zona horaria
        historial["FechaHora"] = pd.to_datetime(historial["FechaHora"], errors='coerce')
        historial["FechaHora"] = historial["FechaHora"].dt.tz_localize('UTC').dt.tz_convert('America/Lima')

        # Filtrar últimos 3 días
        fecha_limite = pd.Timestamp.now(tz='America/Lima') - pd.Timedelta(days=3)
        historial_filtrado = historial[historial["FechaHora"] >= fecha_limite]

        st.subheader("📈 Historial de Predicciones (últimos 3 días)")
        fig = px.scatter(historial_filtrado, x="FechaHora", y="PC",
                         size="Cenizas", color="Cenizas",
                         hover_data=["Cenizas", "PC"],
                         title="Predicciones de Poder Calorífico vs Cenizas",
                         labels={"PC": "Poder Calorífico (kcal/kg)", "FechaHora": "Hora"},
                         template="plotly_dark")
        fig.update_traces(mode="markers+lines")
        st.plotly_chart(fig, use_container_width=True)

        # Tabla interactiva para eliminar
        st.subheader("🧹 Eliminar predicciones del historial")
        st.markdown("Seleccione las filas que desea eliminar:")

        historial_reset = historial.reset_index(drop=True)
        fila_editada = st.data_editor(historial_reset, num_rows="dynamic", use_container_width=True, disabled=["FechaHora", "Cenizas", "PC"], key="editor")

# Mostrar historial editable y permitir eliminación múltiple
st.subheader("🧹 Eliminar puntos del gráfico")

# Resetear el índice para mostrarlo en la tabla
historial_reset = historial.reset_index(drop=True)
fila_editada = st.data_editor(historial_reset, num_rows="dynamic", use_container_width=True)

# Botón para eliminar las filas que fueron eliminadas en el editor
if st.button("🗑️ Eliminar filas seleccionadas"):
    # Comparar los índices para detectar filas eliminadas
    indices_a_eliminar = historial_reset.index.difference(fila_editada.index)
    if not indices_a_eliminar.empty:
        historial_filtrado = historial_reset.drop(indices_a_eliminar)
        historial_filtrado.to_csv(historial_path, index=False)
        st.success("✅ Filas eliminadas correctamente.")
        st.experimental_rerun()
    else:
        st.info("ℹ️ No se detectaron cambios para eliminar.")